import { BrowserProvider, Contract } from 'ethers'

const CONTRACT_ADDRESS = import.meta.env.VITE_ENERGY_TRADE_CONTRACT_ADDRESS
// Populated once the contract ABI is generated by `hardhat compile`.
const CONTRACT_ABI = []

export function getProvider() {
  if (!window.ethereum) {
    throw new Error('No injected wallet found (MetaMask required).')
  }
  return new BrowserProvider(window.ethereum)
}

export async function getSigner() {
  const provider = getProvider()
  return provider.getSigner()
}

export async function getEnergyTradeContract() {
  const signer = await getSigner()
  return new Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer)
}
